### ISSUE TITLE
Estoy utilizando Open 2.0.

### ISSUE THREAD

**Issue by danielmunioz1888** [TodoPago/Plugin-OpenCart#1]
Tengo instalado en mi tienda Open 2.0, y me gustaria utilizar el plugin, tienen pensado desarrollar algo para esto?

**Comment by stradrianstr** [comment]
Yo tambien utilizo Open 2.0! Podrian indicarme que tengo que cambiar para que sea compatible con mi tienda?

**Comment by danielmunioz1888** [comment]
Puedo usar el plugin para 2.0? Veo que no hay respuesta, significa que es compatible?

**Comment by simondole** [comment]
No creo que sean compatibles, son muy distintos entre versiones.
Imposible sacar un usuario para test en la pagina www.todopago.com.ar, te mandan mail de confirmación pero no user y pass para integrar herramientas. Mucha burocracia.  
Alguien contesta estas preguntas??

**Comment by mariano-dim** [comment]
Buenas tardes, aun no tenemos desarrollado este plugin. avisaremos a la comunidad cuando tengamos una versión disponible.

**Comment by mariano-dim** [comment]
Buenas tardes, aun no tenemos desarrollado este plugin. avisaremos a la comunidad cuando tengamos una versión disponible.
