### ISSUE TITLE
Integracion con OC 2.x

### ISSUE THREAD

**Issue by prodos8** [TodoPago/Plugin-OpenCart#3]
Buenos días,
¿Tienen pensado hacer una versión para OpenCart 2.x? Si es así, ¿alguna fecha estimada?
Gracias

**Comment by drarko** [comment]
Estimado,

El plugin para Open Cart 2.x ya se encuentra productivo. Puede obtenerlo en el siguiente repositorio: https://github.com/TodoPago/Plugin-OpenCart2

Gracias
