### ISSUE TITLE
3.0.2.0 compatibilidad

### ISSUE THREAD

**Issue by CheloARG** [TodoPago/Plugin-OpenCart#4]
Hola,
como estan?

Lo planean compatibilizar con la última versión? Es posible que funcione el plugin así como está con la misma? En caso de que no a mis dos preguntas, me recomiendan alguien que pueda "compatibilizarlo" o mismo ustedes, por una tarifa extra?

Gracias.

**Comment by drarko** [comment]
Estimado,
Estamos trabajando en la versión del plugin compatible con OpenCart 3.
A la brevedad estará publicado, comunicaremos oportunamente el release.
Saludos

**Comment by CheloARG** [comment]
Gracias Mauricio.

Disculpa la hora!

Slds.

**Comment by drarko** [comment]
Estimado,
Ya se encuentra publicado el plugin para OpenCart 3.
https://github.com/TodoPago/Plugin-OpenCart

Saludos
